CREATE TABLE IF NOT EXISTS items(id IDENTITY PRIMARY KEY, name VARCHAR (255), price DOUBLE );
DELETE FROM items;
INSERT INTO items VALUES(1, 'Pasta', 400.00);
INSERT INTO items VALUES(2, 'Ramen', 300.00);
INSERT INTO items VALUES(3, 'Coke', 50.00);